* Week %<%W, %G>
** Admin
*** Loose Input [0/3]
- [ ] Gather all scraps of paper, business cards, receipts, and miscellaneous paper. Include stuff on desk. Add to inbox.
- [ ] Go through journal entries for trailing week and add in any loose TODOs
- [ ] Put into inbox any new projects, action items, waiting-fors, someday/maybes, etc., not yet captured.
*** Empty Your Head [0/1]
- [ ] Set a timer for 5 minutes and do brainstorming or mind-mapping
*** Review Action Lists [0/1]
- [ ] Mark off completed actions in tickler/projects/next file. Review for reminders of further action
*** Process Your Notes [0/3]
- [ ] Process email inbox
- [ ] Process physical inbox
- [ ] Process inbox file
*** Review Waiting-For List [0/1]
- [ ] Review WAIT and HOLD items
*** Review Project (and Larger Outcome) Lists [0/2]
- [ ] Review Project file, making sure one current action item is there for each
- [ ] Review Goal file, making sure everything is up to date
*** Review Calendar [0/4]
- [ ] Review scheduled/logged/deadline items for last week
- [ ] Review scheduled/logged/deadline items for next week
- [ ] Review calendar for last week
- [ ] Review calendar for next week
*** Review Any Relevant Checklists [0/2]
- [ ] Review my tickler list, add newly relevant projects to projects
- [ ] Review projects list, remove irrelevant projects to tickler
*** Misc Administration [0/1]
- [ ] Get finances up to date
** Goal tracking
%(zweigtd-reviews-genreview 'goal
   (concat
    "/What did you do that worked well?/\n-  %^{What did you do that worked well?}\n"
    "/What didn't work or got in the way?/\n-  %^{What didn't work or got in the way?}\n"
    "/Should you do anything differently?/\n-  %^{Should you do anything differently?}\n"
    "/What are your priorities for the upcoming week?/\n-  %^{What are you priorities for the upcoming week?}\n")
t t t nil)
** Overall
/How are your goals coming along?/
- %^{How are your goals coming along}
/How do you feel about the review?/
- %^{How do you feel about the review?}
